Description: "Defines group for MFA self-management: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_delegate-permissions_examples.html"

Outputs:
  IAMSelfManagementGroup:
    Value: !Ref "IAMSelfManagementGroup"
  ExecutorAdminGroup:
    Value: !Ref "ExecutorAdminGroup"
  AdminAccessRoleARN:
    Value: !GetAtt "AdminAccessRole.Arn"
  IAMSelfManagementPolicy:
    Value: !Ref "IAMSelfManagementPolicy"

Resources:
  ExecutorAdminGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "ExecutorAccountAdmin"
      Path: "/"
      Policies: 
      - PolicyName: "ExecutorAdmin"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Resource:
            - !Sub "arn:aws:iam::${AWS::AccountId}:role/Admin"
            Condition:
              Bool:
                aws:SecureTransport: True
                aws:MultiFactorAuthPresent: True
              NumericLessThan:
                aws:MultiFactorAuthAge: 7200

  AdminAccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "Admin"
      Path: "/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AdministratorAccess"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              "AWS": !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "sts:AssumeRole"
            Condition:
              Bool:
                aws:SecureTransport: True
                aws:MultiFactorAuthPresent: True
              NumericLessThan:
                aws:MultiFactorAuthAge: 7200

  IAMSelfManagementGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "IAMSelfManagement"
      Path: "/"
      ManagedPolicyArns:
      - !Ref "IAMSelfManagementPolicy"

  IAMSelfManagementPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
        ManagedPolicyName: "IAMSelfManagement"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Sid: "AllowUsersToCreateEnableResyncTheirOwnVirtualMFADevice"
            Effect: "Allow"
            Action:
            - "iam:CreateVirtualMFADevice"
            - "iam:EnableMFADevice"
            - "iam:ResyncMFADevice"
            - "iam:GetUser"
            Resource:
            - !Sub "arn:aws:iam::${AWS::AccountId}:mfa/${!aws:username}"
            - !Sub "arn:aws:iam::${AWS::AccountId}:user/${!aws:username}"

          - Sid: "AllowUsersToDeactivateDeleteTheirOwnVirtualMFADevice"
            Effect: "Allow"
            Action:
            - "iam:DeactivateMFADevice"
            - "iam:DeleteVirtualMFADevice"
            Resource:
            - !Sub "arn:aws:iam::${AWS::AccountId}:mfa/${!aws:username}"
            - !Sub "arn:aws:iam::${AWS::AccountId}:user/${!aws:username}"
            Condition:
              Bool:
                "aws:MultiFactorAuthPresent": "True"

          - Sid: "AllowUsersToListMFADevicesandUsersForConsole"
            Effect: "Allow"
            Action:
            - "iam:ListMFADevices"
            - "iam:ListVirtualMFADevices"
            - "iam:ListUsers"
            Resource: "*"

          - Sid: "AllowMFAdUsersManageAccessKeys"
            Effect: "Allow"
            Action:
            - "iam:DeleteAccessKey"
            - "iam:UpdateAccessKey"
            - "iam:CreateAccessKey"
            - "iam:ListAccessKeys"
            Resource:
            - !Sub "arn:aws:iam::${AWS::AccountId}:user/${!aws:username}"
            Condition:
              Bool:
                "aws:MultiFactorAuthPresent": "True"

          - Sid: "AllowUserToGetAccountPasswordPolicy"
            Effect: "Allow"
            Action:
            - "iam:GetAccountPasswordPolicy"
            Resource: "*"

          - Sid: "AllowMFAdUserToChangeTheirPassword"
            Effect: "Allow"
            Action:
            - "iam:ChangePassword"
            Resource:
            - !Sub "arn:aws:iam::${AWS::AccountId}:user/${!aws:username}"
            Condition:
              Bool:
                "aws:MultiFactorAuthPresent": "True"
